repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.22.0
    hooks:
      - id: gitleaks
        args: ["--staged"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
